clean:
	rm -f myCat
	rm -f sortNumbers
	rm -f dirList
	rm -f myActions



all:		myCat sortNumbers dirList myActions



myCat:		myCat.c
	cc -Wall -O2 myCat.c -o myCat


sortNumbers:		sortNumbers.c
	cc -Wall -O2 sortNumbers.c -o sortNumbers


dirList:		dirList.c
	cc -Wall -O2 dirList.c -o dirList


myActions:		myActions.c
	cc -Wall -O2 myActions.c -o myActions





